name: "CI"
on:
  pull_request:
  push:
jobs:
  dockerimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: project-m36
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: cachix use iohk
      - name: docker load
        run: docker load < $(nix-build docker.nix)
      - name: docker login
        run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login --username ${{secrets.DOCKERHUB_USER}} --password-stdin
      - name: docker tag with version
        run: docker tag project-m36:latest projectm36/project-m36:$(awk '/^Version:/ {print $2}' project-m36.cabal)
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: docker tag latest
        run: docker tag project-m36:latest projectm36/project-m36:latest
        if: ${{ github.ref == 'refs/heads/master' }}
      - run: docker push projectm36/project-m36
        if: ${{ github.ref == 'refs/heads/master' }}

  stack-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc:
          - ghc8.10
          - ghc8.8
          - ghc8.6
        include:
          - os: macos-latest
            ghc: ghc8.10
    steps:
      - name: Setup
        run: |
          echo "::set-env name=stack-yaml::stack.${{ matrix.ghc }}.yaml"
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-stack-${{ env.stack-yaml }}-${{ hashFiles(env.stack-yaml) }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-stack-${{ env.stack-yaml }}-${{ hashFiles(env.stack-yaml) }}
            ${{ runner.os }}-build-stack-${{ env.stack-yaml }}
      - name: Build
        run: stack build --ghc-options -O2 --local-bin-path out --copy-bins
      - name: Test
        run: stack test --stack-yaml=${{ env.stack-yaml }}
      - name: HLint
        run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
      - name: Haddock
        run: stack --no-install-ghc --system-ghc --no-haddock-deps haddock
      - uses: actions/upload-artifact@v2
        with:
          name: project-m36-${{ matrix.os }}-${{ matrix.ghc }}
          path: out/
